---
driver:
  name: vagrant
  synced_folders:
    - ["vagrant", "/vagrant"]
  network:
    - ["forwarded_port", {guest: 4567, host: 4567}]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - example
    attributes:
